version: '2'

services:

  applications:
    image: tianon/true
    volumes:
      - ~/MyCode/laravel-test:/var/www/laravel-test
      - ~/MyCode/laravel-client-one:/var/www/laravel-client-one

  # mysql 数据库服务
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  # redis 服务，用作临时数据缓存
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - "6370:6379"

  # 测试项目
  laravel-test:
    image: docker-registry.khh.space:5000/php-web-server:v1.3
    environment:
      WEBROOT: '/var/www/laravel-test/public'
    extra_hosts:
      - "dockerhost:192.168.31.61"
    volumes_from:
      - applications
    ports:
      - "8001:80"

    # 测试项目2
  laravel-client-one:
    image: docker-registry.khh.space:5000/php-web-server:v1.3
    environment:
      WEBROOT: '/var/www/laravel-client-one/public'
    extra_hosts:
      - "dockerhost:192.168.31.61"
    volumes_from:
      - applications
    ports:
      - "8002:80"

  # workspace
  workspace:
    image: docker-registry.khh.space:5000/workspace
    volumes_from:
      - applications
    tty: true

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
